import { createClient as createServiceClient } from '@supabase/supabase-js'
import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!

const svc = createServiceClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
})

interface RebaitRow {
  trap_id: string
  trap_nr: number | null
  nfc_tag: string | null
  orchard_name: string
  zone_name: string
  lure_type_id: string
  lure_type_name: string
  rebait_weeks: number
  last_rebaited_at: string | null
  weeks_since_rebait: number
  is_overdue: boolean
  is_due_soon: boolean
}

function weeksBadgeHtml(row: RebaitRow): string {
  const wks = Number(row.weeks_since_rebait)
  if (wks >= 999) return '<span style="background:#fdecea;color:#e85a4a;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:700;">Never baited</span>'
  if (row.is_overdue) return `<span style="background:#fdecea;color:#e85a4a;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:700;">OVERDUE · ${wks} wks</span>`
  return `<span style="background:#fff8e1;color:#c49a00;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:700;">Due soon · ${wks} wks</span>`
}

function buildPurchaseListEmail(rows: RebaitRow[], dateStr: string, farmName: string): string {
  // Aggregate by lure type
  const lureMap: Record<string, { name: string; count: number }> = {}
  for (const row of rows) {
    if (!lureMap[row.lure_type_id]) lureMap[row.lure_type_id] = { name: row.lure_type_name, count: 0 }
    lureMap[row.lure_type_id].count++
  }
  const lures = Object.values(lureMap).sort((a, b) => b.count - a.count)
  const total = lures.reduce((sum, l) => sum + l.count, 0)

  const rows_html = lures.map(l => `
    <tr>
      <td style="padding:10px 16px;border-bottom:1px solid #f0f0f0;">${l.name}</td>
      <td style="padding:10px 16px;border-bottom:1px solid #f0f0f0;text-align:center;font-weight:600;">${l.count}</td>
    </tr>`).join('')

  return `
<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f4f4f4;font-family:system-ui,sans-serif;">
<div style="max-width:600px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
  <div style="background:#1c3a2a;padding:28px 32px;">
    <div style="color:#a8d5a2;font-size:13px;font-weight:600;text-transform:uppercase;letter-spacing:1px;margin-bottom:8px;">FarmScout</div>
    <div style="color:#fff;font-size:24px;font-weight:700;">Bait Purchase List</div>
    <div style="color:#6aab80;font-size:14px;margin-top:6px;">${farmName} · Week of ${dateStr}</div>
  </div>
  <div style="padding:28px 32px;">
    <p style="color:#3a4a40;font-size:14px;margin-bottom:20px;">The following lure types are required for upcoming trap rebaiting. Please arrange purchase before the scheduled rebait date.</p>
    <table style="width:100%;border-collapse:collapse;font-size:14px;">
      <thead>
        <tr style="background:#f4f1eb;">
          <th style="padding:10px 16px;text-align:left;color:#7a8a80;font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:0.08em;">Lure Type</th>
          <th style="padding:10px 16px;text-align:center;color:#7a8a80;font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:0.08em;">Qty Needed</th>
        </tr>
      </thead>
      <tbody>
        ${rows_html}
        <tr style="background:#f4f1eb;">
          <td style="padding:10px 16px;font-weight:700;color:#1c3a2a;">Total</td>
          <td style="padding:10px 16px;text-align:center;font-weight:700;color:#1c3a2a;">${total}</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div style="padding:16px 32px;border-top:1px solid #f0ede6;background:#faf9f6;">
    <p style="color:#9aaa9f;font-size:12px;">Generated by FarmScout · Rebait Reminder System</p>
  </div>
</div>
</body></html>`
}

function buildRebaitScheduleEmail(rows: RebaitRow[], dateStr: string, farmName: string): string {
  const rows_html = rows.map(row => `
    <tr>
      <td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;font-weight:600;">T${row.trap_nr ?? row.nfc_tag ?? '?'}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;">${row.orchard_name}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;">${row.zone_name}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;">${row.lure_type_name}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;text-align:center;">${weeksBadgeHtml(row)}</td>
    </tr>`).join('')

  return `
<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f4f4f4;font-family:system-ui,sans-serif;">
<div style="max-width:700px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
  <div style="background:#b36a00;padding:28px 32px;">
    <div style="color:#ffe0a0;font-size:13px;font-weight:600;text-transform:uppercase;letter-spacing:1px;margin-bottom:8px;">FarmScout</div>
    <div style="color:#fff;font-size:24px;font-weight:700;">Rebait Schedule</div>
    <div style="color:#ffd580;font-size:14px;margin-top:6px;">${farmName} · Week of ${dateStr} — ${rows.filter(r => r.is_overdue).length} overdue, ${rows.filter(r => r.is_due_soon && !r.is_overdue).length} due soon</div>
  </div>
  <div style="padding:28px 32px;">
    <p style="color:#3a4a40;font-size:14px;margin-bottom:20px;">The following traps require rebaiting. Overdue traps should be prioritised.</p>
    <div style="overflow-x:auto;">
      <table style="width:100%;border-collapse:collapse;font-size:13px;min-width:560px;">
        <thead>
          <tr style="background:#f4f1eb;">
            <th style="padding:10px 12px;text-align:left;color:#7a8a80;font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;">Trap</th>
            <th style="padding:10px 12px;text-align:left;color:#7a8a80;font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;">Orchard</th>
            <th style="padding:10px 12px;text-align:left;color:#7a8a80;font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;">Zone</th>
            <th style="padding:10px 12px;text-align:left;color:#7a8a80;font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;">Lure</th>
            <th style="padding:10px 12px;text-align:center;color:#7a8a80;font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;">Status</th>
          </tr>
        </thead>
        <tbody>
          ${rows_html}
        </tbody>
      </table>
    </div>
  </div>
  <div style="padding:16px 32px;border-top:1px solid #f0ede6;background:#faf9f6;">
    <p style="color:#9aaa9f;font-size:12px;">Generated by FarmScout · Rebait Reminder System</p>
  </div>
</div>
</body></html>`
}

export async function POST(req: NextRequest) {
  if (!SERVICE_ROLE_KEY) {
    return NextResponse.json({ error: 'Server misconfigured' }, { status: 500 })
  }

  const resendKey = process.env.RESEND_API_KEY
  if (!resendKey) {
    return NextResponse.json({ error: 'RESEND_API_KEY not configured' }, { status: 500 })
  }

  let body: { org_id?: string; farm_id?: string } = {}
  try { body = await req.json() } catch { }

  const orgId = body.org_id
  if (!orgId) return NextResponse.json({ error: 'org_id is required' }, { status: 400 })

  // Call RPC
  const { data: rebaitRows, error: rpcError } = await svc.rpc('get_rebait_summary', {
    p_org_id: orgId,
    ...(body.farm_id ? { p_farm_id: body.farm_id } : {}),
  })

  if (rpcError) return NextResponse.json({ error: rpcError.message }, { status: 500 })
  if (!rebaitRows || rebaitRows.length === 0) {
    return NextResponse.json({ ok: true, purchaseListCount: 0, scheduleCount: 0, message: 'No traps due' })
  }

  // Get farm name + IDs to scope recipients
  let farmIds: string[]
  let farmName = ''
  if (body.farm_id) {
    farmIds = [body.farm_id]
    const { data: farmRow } = await svc.from('farms').select('full_name').eq('id', body.farm_id).single()
    farmName = farmRow?.full_name ?? ''
  } else {
    const { data: farms } = await svc.from('farms').select('id, full_name').eq('organisation_id', orgId).eq('is_active', true)
    farmIds = (farms || []).map((f: { id: string; full_name: string }) => f.id)
  }

  const { data: recipients } = await svc
    .from('rebait_notification_recipients')
    .select('*')
    .in('farm_id', farmIds.length > 0 ? farmIds : ['00000000-0000-0000-0000-000000000000'])
    .eq('is_active', true)

  const resend = new Resend(resendKey)
  const dateStr = new Date().toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' })
  const rows = rebaitRows as RebaitRow[]

  const purchaseListRecipients = (recipients || []).filter(r => r.receives_purchase_list).map(r => r.email)
  const scheduleRecipients = (recipients || []).filter(r => r.receives_rebait_schedule).map(r => r.email)

  const promises: Promise<unknown>[] = []

  if (purchaseListRecipients.length > 0) {
    promises.push(
      resend.emails.send({
        from: 'FarmScout <noreply@farmscout.app>',
        to: purchaseListRecipients,
        subject: `FarmScout — Bait Purchase List${farmName ? ` · ${farmName}` : ''} (Week of ${dateStr})`,
        html: buildPurchaseListEmail(rows, dateStr, farmName),
      })
    )
  }

  if (scheduleRecipients.length > 0) {
    promises.push(
      resend.emails.send({
        from: 'FarmScout <noreply@farmscout.app>',
        to: scheduleRecipients,
        subject: `FarmScout — Rebait Schedule${farmName ? ` · ${farmName}` : ''} (Next Week)`,
        html: buildRebaitScheduleEmail(rows, dateStr, farmName),
      })
    )
  }

  await Promise.all(promises)

  return NextResponse.json({
    ok: true,
    purchaseListCount: purchaseListRecipients.length,
    scheduleCount: scheduleRecipients.length,
  })
}
