// Supabase Edge Function — weekly-rebait-report
// Runs daily via cron (every day at 05:00 UTC).
// Checks which farms have send_day_of_week = today's DOW and sends emails.
// Deploy: supabase functions deploy weekly-rebait-report
// Secret:  supabase secrets set RESEND_API_KEY=re_xxx

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'

const SUPABASE_URL = Deno.env.get('SUPABASE_URL') ?? ''
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY') ?? ''

interface RebaitRow {
  trap_id: string
  trap_nr: number | null
  nfc_tag: string | null
  orchard_name: string
  zone_name: string
  lure_type_id: string
  lure_type_name: string
  rebait_weeks: number
  last_rebaited_at: string | null
  weeks_since_rebait: number
  is_overdue: boolean
  is_due_soon: boolean
}

function svcHeaders() {
  return {
    apikey: SERVICE_ROLE_KEY,
    Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
    'Content-Type': 'application/json',
  }
}

async function dbGet(path: string) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, { headers: svcHeaders() })
  return res.json()
}

async function dbRpc(name: string, body: Record<string, unknown>) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`, {
    method: 'POST',
    headers: svcHeaders(),
    body: JSON.stringify(body),
  })
  return res.json()
}

async function sendEmail(to: string[], subject: string, html: string) {
  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'FarmScout <noreply@farmscout.app>',
      to,
      subject,
      html,
    }),
  })
  return res.ok
}

function buildPurchaseHtml(rows: RebaitRow[], dateStr: string): string {
  const lureMap: Record<string, { name: string; count: number }> = {}
  for (const row of rows) {
    if (!lureMap[row.lure_type_id]) lureMap[row.lure_type_id] = { name: row.lure_type_name, count: 0 }
    lureMap[row.lure_type_id].count++
  }
  const lures = Object.values(lureMap).sort((a, b) => b.count - a.count)
  const total = lures.reduce((s, l) => s + l.count, 0)
  const rows_html = lures.map(l =>
    `<tr><td style="padding:10px 16px;border-bottom:1px solid #f0f0f0;">${l.name}</td><td style="padding:10px 16px;border-bottom:1px solid #f0f0f0;text-align:center;font-weight:600;">${l.count}</td></tr>`
  ).join('')
  return `<!DOCTYPE html><html><body style="font-family:system-ui,sans-serif;background:#f4f4f4;margin:0;padding:0;">
<div style="max-width:600px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;">
<div style="background:#1c3a2a;padding:28px 32px;"><div style="color:#a8d5a2;font-size:13px;margin-bottom:8px;">FarmScout</div><div style="color:#fff;font-size:24px;font-weight:700;">Bait Purchase List</div><div style="color:#6aab80;font-size:14px;margin-top:6px;">Week of ${dateStr}</div></div>
<div style="padding:28px 32px;"><table style="width:100%;border-collapse:collapse;font-size:14px;"><thead><tr style="background:#f4f1eb;"><th style="padding:10px 16px;text-align:left;color:#7a8a80;font-size:12px;">Lure Type</th><th style="padding:10px 16px;text-align:center;color:#7a8a80;font-size:12px;">Qty</th></tr></thead><tbody>${rows_html}<tr style="background:#f4f1eb;"><td style="padding:10px 16px;font-weight:700;">Total</td><td style="padding:10px 16px;text-align:center;font-weight:700;">${total}</td></tr></tbody></table></div>
<div style="padding:16px 32px;border-top:1px solid #f0ede6;background:#faf9f6;"><p style="color:#9aaa9f;font-size:12px;">Generated by FarmScout · Rebait Reminder System</p></div>
</div></body></html>`
}

function buildScheduleHtml(rows: RebaitRow[], dateStr: string): string {
  const rows_html = rows.map(row => {
    const wks = Number(row.weeks_since_rebait)
    const badge = wks >= 999
      ? '<span style="background:#fdecea;color:#e85a4a;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:700;">Never</span>'
      : row.is_overdue
        ? `<span style="background:#fdecea;color:#e85a4a;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:700;">OVERDUE ${wks}w</span>`
        : `<span style="background:#fff8e1;color:#c49a00;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:700;">Due soon ${wks}w</span>`
    return `<tr><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;font-weight:600;">T${row.trap_nr ?? '?'}</td><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;">${row.orchard_name}</td><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;">${row.zone_name}</td><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;">${row.lure_type_name}</td><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;text-align:center;">${badge}</td></tr>`
  }).join('')
  return `<!DOCTYPE html><html><body style="font-family:system-ui,sans-serif;background:#f4f4f4;margin:0;padding:0;">
<div style="max-width:700px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;">
<div style="background:#b36a00;padding:28px 32px;"><div style="color:#ffe0a0;font-size:13px;margin-bottom:8px;">FarmScout</div><div style="color:#fff;font-size:24px;font-weight:700;">Rebait Schedule</div><div style="color:#ffd580;font-size:14px;margin-top:6px;">Next week — ${dateStr}</div></div>
<div style="padding:28px 32px;overflow-x:auto;"><table style="width:100%;border-collapse:collapse;font-size:13px;"><thead><tr style="background:#f4f1eb;"><th style="padding:10px 12px;text-align:left;color:#7a8a80;font-size:11px;">Trap</th><th style="padding:10px 12px;text-align:left;color:#7a8a80;font-size:11px;">Orchard</th><th style="padding:10px 12px;text-align:left;color:#7a8a80;font-size:11px;">Zone</th><th style="padding:10px 12px;text-align:left;color:#7a8a80;font-size:11px;">Lure</th><th style="padding:10px 12px;text-align:center;color:#7a8a80;font-size:11px;">Status</th></tr></thead><tbody>${rows_html}</tbody></table></div>
<div style="padding:16px 32px;border-top:1px solid #f0ede6;background:#faf9f6;"><p style="color:#9aaa9f;font-size:12px;">Generated by FarmScout · Rebait Reminder System</p></div>
</div></body></html>`
}

serve(async (_req: Request) => {
  try {
    // Today's day-of-week in UTC (0=Sun, 1=Mon, … 6=Sat)
    const todayDow = new Date().getUTCDay()

    // Get all active farms with notification settings for today's DOW
    const settings: any[] = await dbGet(
      `rebait_notification_settings?send_day_of_week=eq.${todayDow}&is_active=eq.true&select=organisation_id,farm_id`
    )

    if (!settings || settings.length === 0) {
      return new Response(JSON.stringify({ ok: true, message: 'No farms scheduled today' }), {
        headers: { 'Content-Type': 'application/json' },
      })
    }

    const dateStr = new Date().toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' })
    let emailsSent = 0

    for (const setting of settings) {
      try {
        const { organisation_id: orgId, farm_id: farmId } = setting

        // Get rebait summary for this farm
        const rows: RebaitRow[] = await dbRpc('get_rebait_summary', {
          p_org_id: orgId,
          p_farm_id: farmId,
        })

        if (!rows || rows.length === 0) continue

        // Get recipients for this farm
        const recipients: any[] = await dbGet(
          `rebait_notification_recipients?farm_id=eq.${farmId}&is_active=eq.true&select=email,receives_purchase_list,receives_rebait_schedule`
        )

        if (!recipients || recipients.length === 0) continue

        const purchaseRecipients = recipients.filter(r => r.receives_purchase_list).map(r => r.email)
        const scheduleRecipients = recipients.filter(r => r.receives_rebait_schedule).map(r => r.email)

        if (purchaseRecipients.length > 0) {
          const ok = await sendEmail(
            purchaseRecipients,
            `FarmScout — Bait Purchase List (Week of ${dateStr})`,
            buildPurchaseHtml(rows, dateStr)
          )
          if (ok) emailsSent += purchaseRecipients.length
        }

        if (scheduleRecipients.length > 0) {
          const ok = await sendEmail(
            scheduleRecipients,
            `FarmScout — Rebait Schedule (Next Week)`,
            buildScheduleHtml(rows, dateStr)
          )
          if (ok) emailsSent += scheduleRecipients.length
        }
      } catch (err) {
        console.error(`[weekly-rebait-report] Error processing farm ${setting.farm_id}:`, err)
      }
    }

    return new Response(JSON.stringify({ ok: true, farmsProcessed: settings.length, emailsSent }), {
      headers: { 'Content-Type': 'application/json' },
    })
  } catch (err) {
    console.error('[weekly-rebait-report] Fatal error:', err)
    return new Response(JSON.stringify({ ok: false, error: String(err) }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    })
  }
})
