import { createServerClient } from '@supabase/ssr'
import { createClient } from '@supabase/supabase-js'
import { NextRequest, NextResponse } from 'next/server'
import { buildHrPdf, EventData } from '@/lib/hr-pdf'
import { Resend } from 'resend'

function anonSupabase(req: NextRequest) {
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { cookies: { getAll() { return req.cookies.getAll() }, setAll() {} } }
  )
}

function svcSupabase() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  )
}

function buildNotificationEmail(
  eventTypeName: string, employeeName: string, employeeNr: string,
  farmName: string, eventDate: string, reason: string,
): string {
  const typeColors: Record<string, string> = {
    'Red Light': '#c62828', 'Green Light': '#2e7d32',
    'Schedule Disciplinary Hearing': '#e65100',
    'Verbal Warning': '#f9a825', 'Absenteeism Formal Letter': '#f9a825',
    'First Written Warning': '#ef6c00', 'Second Written Warning': '#d84315',
    'Final Written Warning': '#b71c1c',
  }
  const color = typeColors[eventTypeName] || '#333'

  return `<!DOCTYPE html><html><head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#f4f4f4;font-family:system-ui,sans-serif;">
<div style="max-width:600px;margin:32px auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">
  <div style="background:#1a2340;padding:24px 32px;">
    <div style="color:#7a9fd4;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:1px;margin-bottom:6px;">FarmScout HR</div>
    <div style="color:#fff;font-size:20px;font-weight:700;">Disciplinary Event Created</div>
  </div>
  <div style="padding:28px 32px;">
    <div style="display:inline-block;background:${color}15;color:${color};padding:6px 16px;border-radius:20px;font-size:13px;font-weight:700;margin-bottom:20px;">${eventTypeName}</div>
    <table style="width:100%;font-size:14px;color:#333;border-collapse:collapse;">
      <tr><td style="padding:8px 0;color:#888;width:130px;">Employee</td><td style="padding:8px 0;font-weight:600;">${employeeName}</td></tr>
      <tr><td style="padding:8px 0;color:#888;">Employee Nr</td><td style="padding:8px 0;">${employeeNr}</td></tr>
      <tr><td style="padding:8px 0;color:#888;">Farm</td><td style="padding:8px 0;">${farmName}</td></tr>
      <tr><td style="padding:8px 0;color:#888;">Date</td><td style="padding:8px 0;">${eventDate}</td></tr>
      <tr><td style="padding:8px 0;color:#888;vertical-align:top;">Reason</td><td style="padding:8px 0;">${reason || '\u2014'}</td></tr>
    </table>
    <p style="color:#888;font-size:12px;margin-top:24px;">The formal document is attached as a PDF. Print, sign, and upload the signed copy back to FarmScout.</p>
  </div>
  <div style="padding:16px 32px;border-top:1px solid #f0f0f0;background:#fafafa;">
    <p style="color:#999;font-size:11px;margin:0;">Generated by FarmScout HR Module</p>
  </div>
</div>
</body></html>`
}

export async function POST(req: NextRequest) {
  const anon = anonSupabase(req)
  const { data: { user } } = await anon.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const resendKey = process.env.RESEND_API_KEY
  if (!resendKey) return NextResponse.json({ error: 'RESEND_API_KEY not configured' }, { status: 500 })

  let body: { event_id?: string; to?: string[] } = {}
  try { body = await req.json() } catch {}

  const { event_id, to } = body
  if (!event_id) return NextResponse.json({ error: 'event_id required' }, { status: 400 })
  if (!to || to.length === 0) return NextResponse.json({ error: 'to (email addresses) required' }, { status: 400 })

  const svc = svcSupabase()

  const { data: event, error } = await svc
    .from('hr_events')
    .select('*, hr_event_types(name), qc_employees(full_name, employee_nr), farms(full_name, logo_url)')
    .eq('id', event_id)
    .single()

  if (error || !event) return NextResponse.json({ error: 'Event not found' }, { status: 404 })

  const eventTypeName = event.hr_event_types?.name ?? 'Event'
  const employeeName = event.qc_employees?.full_name ?? 'Unknown'
  const employeeNr = event.qc_employees?.employee_nr ?? ''
  const farmName = event.farms?.full_name ?? ''

  const d: EventData = {
    employeeName, employeeNr,
    reason: event.reason ?? '',
    comments: event.comments ?? '',
    eventDate: event.event_date,
    farmName,
    chairPerson: event.chair_person ?? '',
    logoUrl: event.farms?.logo_url ?? null,
  }

  const pdfBytes = await buildHrPdf(eventTypeName, d)
  const filename = `${eventTypeName} - ${employeeName} - ${event.event_date}.pdf`.replace(/[^a-zA-Z0-9 ._-]/g, '')
  const html = buildNotificationEmail(eventTypeName, employeeName, employeeNr, farmName, event.event_date, event.reason ?? '')

  const resend = new Resend(resendKey)
  const { error: sendError } = await resend.emails.send({
    from: 'FarmScout <noreply@farmscout.app>',
    to,
    subject: `HR: ${eventTypeName} \u2014 ${employeeName} (${event.event_date})`,
    html,
    attachments: [{ filename, content: Buffer.from(pdfBytes).toString('base64') }],
  })

  if (sendError) return NextResponse.json({ error: sendError.message }, { status: 500 })

  return NextResponse.json({ ok: true, recipientCount: to.length })
}
